name: release
on:
  push:
    tags:
      - "**"
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Fetch all history 
          fetch-depth: 0
      - name: Setup Java 25
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '25'
      - name: Maven Publish
        id: maven_publish
        env:
          ARCHIVE_URL: ${{ secrets.TEACON_ARCHIVE_URL }}
          ARCHIVE_ENDPOINT: ${{ secrets.TEACON_ARCHIVE_ENDPOINT }}
          ARCHIVE_ACCESS_KEY: ${{ secrets.TEACON_ARCHIVE_ACCESS_KEY }}
          ARCHIVE_SECRET_KEY: ${{ secrets.TEACON_ARCHIVE_SECRET_KEY }}
        run: |
          chmod +x ./gradlew
          ./gradlew -Dorg.gradle.s3.endpoint=$ARCHIVE_ENDPOINT publish
